version: '2'
services:
  web:
    build: ./services/httpd
    volumes: 
      - ./webroot:/webroot
      - ./logs:/log
    ports: 
      - 8080:80
    depends_on:
      - php
  php:
    build: ./services/php
    volumes: 
      - ./webroot:/webroot
  db:
    image: mysql
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080