version: '3'
services:
  web:
    build: 
      context: ./services/php-apache
      args:
        - USER_ID=1000 # use the command "id" to determine your current userId
    volumes:
      - ./webroot:/webroot:cached
    ports:
      - 8080:80
  db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql:cached
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080