version: '3'
services:
  web:
    build: ./services/php-apache
    volumes:
      - ./webroot:/webroot
    ports:
      - 8080:80
  db:
    image: mariadb
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8181:80
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080