version: '3'

networks:
  dbg:

volumes:
    mysql-data:
    mongo-data:

services:
  #Console
  console:
    container_name: dbg_console
    build:
      context: ./console
    volumes:
      - ./data/dataswitcher_aws:/dataswitcher
      - ./data/databrydge_aws:/databrydge
    depends_on:
      - mariadb
      - mongodb
    networks:
      - dbg
    command: tail -f /dev/null
    environment:
      PHP_IDE_CONFIG: "serverName=xdebug.test"
  #Web
  web:
    container_name: dbg_web
    build: 
      context: ./build
      args:
        - USER_ID=10000
    volumes:
      - ./data/dataswitcher_aws:/var/www/html/dataswitcher_aws/
      - ./data/databrydge_aws:/var/www/html/databrydge_aws/
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    depends_on: 
      - mariadb
      - mongodb
    networks:
      - dbg

  #MongoDB
  mongodb:
    image: mongo:latest
    container_name: dbg_mongodb
    environment:
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo-data:/data/db
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - dbg
    command:
      'mongod --smallfiles --logpath=/dev/null' # --quiet

  #MariaDB
  mariadb:
    container_name: dbg_mariadb
    image: mariadb:10.3
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    networks:
      - dbg
    command:
      'mysqld --innodb-flush-method=fsync'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: db
      MYSQL_PASSWORD: db
      MYSQL_DATABASE: db

  #PhpMyAdmin
  phpmyadmin:
    container_name: dbg_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 127.0.0.1:8180:80
    networks:
      - dbg
    depends_on: 
      - mariadb
    links:
      - mariadb
    environment:
      PMA_PORT: 3306
      PMA_HOST: mariadb