version: '2'
services:
  web:
    build: .
    volumes:
      - ./src:/var/www/html
      - ./log:/var/www/log
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: mysql
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 33061:3306
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_USER: db
     MYSQL_PASSWORD: db
     MYSQL_DATABASE: db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
          - 8181:80
  mailcatcher:
    image: schickling/mailcatcher
    ports:
          - 1080:1080
